src/debian_reimbursements/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("registration.backends.default.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("requests/", include("reimbursements.urls")),
    path("", include("webui.urls")),
]

src/reimbursements/urls.py
from django.urls import path

from reimbursements.views import (
    BankDetailsView,
    ReceiptCreateView,
    ReceiptDeleteView,
    ReceiptEditView,
    ReceiptFileView,
    RequestCommentView,
    RequestCreateView,
    RequestEditView,
    RequestReceiptsView,
    RequestReimburseView,
    RequestReimburseReturnView,
    RequestReviewView,
    RequestSubmitDraftView,
    RequestSubmitIncreaseView,
    RequestSubmitView,
    RequestView,
)

urlpatterns = [
    path("new", RequestCreateView.as_view(), name="request-new"),
    path("<int:pk>", RequestView.as_view(), name="request"),
    path("<int:pk>/edit", RequestEditView.as_view(), name="request-edit"),
    path(
        "<int:pk>/submit-draft",
        RequestSubmitDraftView.as_view(),
        name="request-submit-draft",
    ),
    path("<int:pk>/review", RequestReviewView.as_view(), name="request-review"),
    path("<int:pk>/bank-details", BankDetailsView.as_view(), name="bank-details"),
    path("<int:pk>/submit", RequestSubmitView.as_view(), name="request-submit"),
    path(
        "<int:pk>/reimburse", RequestReimburseView.as_view(), name="request-reimburse"
    ),
    path(
        "<int:pk>/reimburse-return",
        RequestReimburseReturnView.as_view(),
        name="request-reimburse-return",
    ),
    path(
        "<int:pk>/request-increase",
        RequestSubmitIncreaseView.as_view(),
        name="request-submit-increase",
    ),
    path(
        "<int:pk>/request-comment",
        RequestCommentView.as_view(),
        name="request-comment",
    ),
    path("<int:pk>/receipts", RequestReceiptsView.as_view(), name="request-receipts"),
    path(
        "<int:request_id>/receipts/new", ReceiptCreateView.as_view(), name="add-receipt"
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/delete",
        ReceiptDeleteView.as_view(),
        name="delete-receipt",
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/edit",
        ReceiptEditView.as_view(),
        name="edit-receipt",
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/view-file",
        ReceiptFileView.as_view(),
        name="view-receipt-file",
    ),
]

src/webui/urls.py
from django.urls import path

from webui.views import IndexView, ProfileView

urlpatterns = [
    path("", IndexView.as_view()),
    path("profile", ProfileView.as_view(), name="profile"),
]

src/reimbursements/models.py
from collections import defaultdict
from decimal import Decimal

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from historical_currencies.exceptions import ExchangeRateUnavailable
from historical_currencies.exchange import exchange

from reimbursements.storage import generate_receipt_filename, receipts_storage


User = get_user_model()


class SoftDeletionManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class Profile(models.Model):
    bank_details = models.JSONField(blank=True)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"Profile for {self.user}"


class RequestType(models.Model):
    name = models.CharField(max_length=50)
    deleted = models.BooleanField(default=False)

    objects = SoftDeletionManager()
    all_objects = models.Manager()

    def __str__(self):
        return self.name

    @classmethod
    def expense_type_map(cls):
        output = defaultdict(list)
        for row in RequestType.expense_types.through.objects.all():
            output[row.requesttype_id].append(row.expensetype_id)
        return output


class ExpenseType(models.Model):
    request_types = models.ManyToManyField(RequestType, related_name="expense_types")
    name = models.CharField(max_length=50, unique=True)
    deleted = models.BooleanField(default=False)

    objects = SoftDeletionManager()
    all_objects = models.Manager()

    def __str__(self):
        return self.name


class ExpenseTypeAllocation:
    def __init__(
        self, name, currency, requested=0, spent=0, reimbursed=0, special=False
    ):
        self.name = name
        self.currency = currency
        self.requested = Decimal(requested)
        self.spent = Decimal(spent)
        self.reimbursed = Decimal(reimbursed)
        self.special = special

    @property
    def qualified_requested(self):
        return (self.requested, self.currency)

    @property
    def qualified_spent(self):
        return (self.spent, self.currency)

    @property
    def qualified_reimbursed(self):
        return (self.reimbursed, self.currency)

    @property
    def remaining(self):
        return self.requested - self.spent

    @property
    def qualified_remaining(self):
        return (self.remaining, self.currency)

    @property
    def over_budget(self):
        return self.spent > self.requested

    @property
    def within_budget(self):
        return not self.over_budget

    @property
    def approved(self):
        if self.within_budget:
            return self.requested
        return self.requested * (
            1 + Decimal(settings.OVERBUDGET_LEEWAY_PERCENTAGE) / 100
        )

    @property
    def reimburseable(self):
        return min(self.approved, self.spent)

    @property
    def qualified_approved(self):
        return (self.approved, self.currency)

    @property
    def qualified_reimburseable(self):
        return (self.reimburseable, self.currency)

    def to_dict(self):
        return {
            "currency": self.currency,
            "requested": float(self.requested),
            "spent": float(self.spent),
            "reimbursed": float(self.reimbursed),
        }


class Request(models.Model):
    class States(models.TextChoices):
        DRAFT = "draft", _("Draft")
        PENDING_APPROVAL = "pending_approval", _("Pending Approval")
        APPROVED = "approved", _("Approved")
        DELETED = "deleted", _("Deleted")
        PENDING_PAYMENT = "pending_payment", _("Pending Payment")
        PAID = "paid", _("Paid")

    requester = models.ForeignKey(User, on_delete=models.PROTECT)
    parent = models.ForeignKey(
        "Request",
        on_delete=models.PROTECT,
        null=True,
        related_name="children",
        blank=True,
    )
    state = models.CharField(
        max_length=16, choices=States.choices, default=States.DRAFT
    )
    bank_details = models.JSONField(null=True, blank=True)
    request_type = models.ForeignKey(RequestType, on_delete=models.PROTECT)
    description = models.TextField()
    currency = models.CharField(max_length=3, default=settings.DEFAULT_CURRENCY)
    approver_group = models.ForeignKey(
        Group, on_delete=models.PROTECT, null=True, related_name="requests_approver"
    )
    payer_group = models.ForeignKey(
        Group, on_delete=models.PROTECT, related_name="requests_payer"
    )

    @property
    def subject(self):
        lines = self.description.splitlines()
        if lines:
            return lines[0].strip()
        return ""

    @property
    def total(self):
        return (
            self.lines.aggregate(total=models.Sum("amount"))["total"] or Decimal(0),
            self.currency,
        )

    @property
    def receipts_total(self):
        lines = ReceiptLine.objects.filter(receipt__request=self)
        return (
            lines.aggregate(total=models.Sum("converted_amount"))["total"]
            or Decimal(0),
            self.currency,
        )

    @property
    def reimbursed_total(self):
        lines = ReimbursementLine.objects.filter(request=self)
        return (
            lines.aggregate(total=models.Sum("amount"))["total"] or Decimal(0),
            self.currency,
        )

    @property
    def created(self):
        return self.history.get(event=RequestHistory.Events.CREATED).timestamp

    @property
    def updated(self):
        return self.history.all().last().timestamp

    def get_absolute_url(self):
        return reverse("request", kwargs={"pk": self.pk})

    def get_fully_qualified_url(self):
        return settings.SITE_URL.rstrip("/") + self.get_absolute_url()

    def summarize_by_type(self):
        summary = {}
        total = ExpenseTypeAllocation("Total", self.currency, special=True)
        for line in self.lines.all():
            if line.expense_type_id not in summary:
                summary[line.expense_type_id] = ExpenseTypeAllocation(
                    line.expense_type.name, self.currency
                )
            summary[line.expense_type_id].requested += line.amount
            total.requested += line.amount
        for line in self.reimbursement_lines.all():
            if line.expense_type_id not in summary:
                summary[line.expense_type_id] = ExpenseTypeAllocation(
                    line.expense_type.name, self.currency
                )
            summary[line.expense_type_id].reimbursed += line.amount
            total.reimbursed += line.amount
        for receipt in self.receipts.all():
            for line in receipt.lines.all():
                if line.expense_type_id not in summary:
                    summary[line.expense_type_id] = ExpenseTypeAllocation(
                        line.expense_type.name, self.currency
                    )
                summary[line.expense_type_id].spent += line.converted_amount
                total.spent += line.converted_amount
        summary["total"] = total
        return summary

    def summarize_by_type_dict(self):
        allocation = {}
        for k, v in self.summarize_by_type().items():
            allocation[v.name] = v.to_dict()
        return allocation

    @property
    def approved_budget_limit(self):
        """The total requested, plus acceptable leeway"""
        total = self.total[0]
        approved_limit = total * (
            1 + Decimal(settings.OVERBUDGET_LEEWAY_PERCENTAGE) / 100
        )
        return (approved_limit, self.currency)

    @property
    def total_reimburseable(self):
        """The total requested, cut off at approved_budget_limit"""
        approved_total = min(self.approved_budget_limit[0], self.receipts_total[0])
        return (approved_total, self.currency)

    @property
    def within_budget(self):
        budget = self.approved_budget_limit[0]
        receipts_total = self.receipts_total[0]
        return receipts_total <= budget

    @property
    def over_budget(self):
        return not self.within_budget

    def __str__(self):
        return f"Request {self.id}: {self.subject}"

    def user_access(self, user):
        """What access levels does user have to this Request"""
        access = {}
        if self.requester == user:
            access["requester"] = True
        if user.groups.filter(id=self.approver_group_id).exists():
            access["approver"] = True
        if user.groups.filter(id=self.payer_group_id).exists():
            access["payer"] = True
        return access

    @property
    def requester_name(self):
        """Helper for templates, to render the requester's name"""
        name = self.requester.get_full_name()
        if not name:
            name = self.requester.username
        return name


class RequestLine(models.Model):
    request = models.ForeignKey(Request, on_delete=models.CASCADE, related_name="lines")
    expense_type = models.ForeignKey(ExpenseType, on_delete=models.PROTECT)
    description = models.TextField()
    amount = models.DecimalField(decimal_places=2, max_digits=15)

    @property
    def qualified_amount(self):
        return (self.amount, self.request.currency)

    def clean(self):
        super().clean()
        request_type_id = self.request.request_type_id
        if (
            request_type_id
            and self.expense_type_id
            and not self.expense_type.request_types.filter(pk=request_type_id)
        ):
            raise ValidationError(
                {
                    "expense_type": _("%s is not a valid expense type for %s requests")
                    % (self.expense_type.name, self.request.request_type.name),
                }

src/reimbursements/templates/reimbursements/bank_details.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_title %}
{% trans "Add Bank Details" %}
{% endblock %}
{% block content %}
<h1>{% trans "Add Bank Details" %}</h1>
<p>
  {% blocktrans %}
    Please entere the appropriate details for your bank. If you are unsure, fill
    in as much of the form as you can.
  {% endblocktrans %}
</p>
<form method="post">
  {% crispy form %}
  <input type="submit" class="btn btn-primary" value="{% trans 'Save' %}">
</form>
{% endblock %}

src/reimbursements/templates/reimbursements/edit_receipt.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_title %}
  {{ view.request_model.subject }}:
  {% if object %}
    {% trans "Edit Receipt" %}
  {% else %}
    {% trans "New Receipt" %}
  {% endif %}
{% endblock %}
{% block content %}
<h1>
  {{ view.request_model.subject }}:
  {% if object %}
    {% trans "Edit Receipt" %}
  {% else %}
    {% trans "New Receipt" %}
  {% endif %}
</h1>
{% if object.pk %}
  <form method="post" action="{% url "delete-receipt" view.request_model.id object.id %}" class="d-inline">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" name="delete"
           value="{% trans "Delete Receipt" %}">
  </form>
  <a class="btn btn-info" href="{% url "view-receipt-file" view.request_model.id object.id %}">View File</a>
{% endif %}
<form method="post" enctype="multipart/form-data">
  {% crispy form %}
  <h2>{% trans "Receipt Lines" %}</h2>
  <div class="form-text">
    {% blocktrans %}
      Break up the receipt into a couple of lines, if necessary.
      Most of the time you only need a single line to capture a receipt, but
      you can use more, if necessary.
    {% endblocktrans %}
  </div>
  <div class="form-text">
    {% blocktrans %}
      Please accurately record the total (or, if necessary lines) of the receipt.
      If you are not requesting full reimbursement for the invoice, list the
      relevant lines and values only and note that the request is partial, in
      the description.
    {% endblocktrans %}
  </div>
  {% crispy formset formset_helper %}
  <div class="fs-4 pb-3">
    {% trans "Total:" %}
    <span id="total">{% trans "Calculated by Javascript..." %}</span>
  </div>
  <a class="btn btn-secondary" id="add_line">{% trans "Add Line" %}</a>
  <input type="submit" class="btn btn-primary" value="{% trans 'Save' %}">
</form>
{% endblock %}
{% block extra_foot %}
{{ valid_expense_types|json_script:"valid_expense_types"}}
<script>
  "use strict";
  (function() {
    const update_total = function(event) {
      var totals = {};
      document.querySelectorAll("form tbody tr:not(.empty-form)").forEach(row => {
        const deleted = row.querySelector("input[id$=-DELETE").checked;
        const currency = row.querySelector("select[id$=-currency]").value;
        const amount = parseFloat(row.querySelector("input[id$=-amount]").value) || 0;
        if (!deleted) {
          totals[currency] = (totals[currency] || 0) + amount;
        }
      });
      var rendered = '';
      for (const currency in totals) {
        if (rendered) {
          rendered += ", ";
        }
        rendered += new Intl.NumberFormat("en-US", {
          style: "currency",
          currency: currency,
        }).format(totals[currency]);
      }
      document.querySelector("span#total").textContent = rendered;
    }

    const update_total_listener_selector = "select[id$=-currency], input[id$=-amount], input[id$=-DELETE]";
    document.querySelectorAll(update_total_listener_selector).forEach(el => {
      el.addEventListener("input", update_total);
    });
    update_total();

    const add_button = document.querySelector("#add_line");
    add_button.addEventListener("click", (event) => {
      const total_forms_input = document.querySelector("#id_lines-TOTAL_FORMS");
      const index = parseInt(total_forms_input.getAttribute("value"));
      const empty_form = document.querySelector(".empty-form");
      const new_form = empty_form.innerHTML.replace(/__prefix__/g, index);
      empty_form.parentElement.insertAdjacentHTML("beforeend", new_form);
      const new_row = empty_form.parentElement.lastElementChild;
      total_forms_input.setAttribute("value", index + 1);
      new_row.querySelectorAll(update_total_listener_selector).forEach(el => {
        el.addEventListener("input", update_total);
      });
    });

    const valid_expense_types = JSON.parse(
      document.getElementById("valid_expense_types").textContent);
    document.querySelectorAll("select[id$=-expense_type]").forEach(el => {
      el.querySelectorAll("option").forEach(opt => {
        if (opt.value) {
          opt.disabled = !valid_expense_types.includes(parseInt(opt.value));
        }
      });
    });
  })();
</script>
{% endblock %}

src/reimbursements/templates/reimbursements/edit_request.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_title %}
  {% if object %}
    {% trans "Edit Request" %}
  {% else %}
    {% trans "New Request" %}
  {% endif %}
{% endblock %}
{% block content %}
<h1>
  {% if object %}
    {% trans "Edit Request" %}
  {% else %}
    {% trans "New Request" %}
  {% endif %}
</h1>
<p>
  {% blocktrans %}
    This is a request for budget pre-approval to make an expense for the
    project.
    You don't need to break it down into every expected item, just into broad
    categories, for review of your request.
    Once approved, you may make the expenses and will get an opportunity to
    upload receipts.
  {% endblocktrans %}
</p>
<form method="post">
  {% crispy form %}
  {% crispy formset formset_helper %}
  <div class="fs-4 pb-3">
    {% trans "Total:" %}
    <span id="total">{% trans "Calculated by Javascript..." %}</span>
  </div>
  <a class="btn btn-secondary" id="add_line">{% trans "Add Item" %}</a>
  <input type="submit" class="btn btn-primary" value="{% trans 'Save Draft' %}">
</form>
{% endblock %}
{% block extra_foot %}
{{ expense_type_map|json_script:"expense_type_map"}}
<script>
  "use strict";
  (function() {
    const update_total = function(event) {
      var total = 0;
      document.querySelectorAll("form tbody tr:not(.empty-form)").forEach(row => {
        const deleted = row.querySelector("input[id$=-DELETE").checked;
        const amount = parseFloat(row.querySelector("input[id$=-amount]").value) || 0;
        if (!deleted) {
          total += amount;
        }
      });
      const currency = document.querySelector("select#id_currency").value;
      const rendered = new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: currency,
      }).format(total);
      document.querySelector("span#total").textContent = rendered;
    }

    document.querySelector("select#id_currency").addEventListener("input", update_total);
    const update_total_listener_selector = "input[id$=-amount], input[id$=-DELETE]";
    document.querySelectorAll(update_total_listener_selector).forEach(el => {
      el.addEventListener("input", update_total);
    });
    update_total();

    const add_button = document.querySelector("#add_line");
    add_button.addEventListener("click", (event) => {
      const total_forms_input = document.querySelector("#id_lines-TOTAL_FORMS");
      const index = parseInt(total_forms_input.getAttribute("value"));
      const empty_form = document.querySelector(".empty-form");
      const new_form = empty_form.innerHTML.replace(/__prefix__/g, index);
      empty_form.parentElement.insertAdjacentHTML("beforeend", new_form);
      const new_row = empty_form.parentElement.lastElementChild;
      total_forms_input.setAttribute("value", index + 1);
      new_row.querySelectorAll(update_total_listener_selector).forEach(el => {
        el.addEventListener("input", update_total);
      });
    });

    const expense_type_map = JSON.parse(
      document.getElementById("expense_type_map").textContent);
    const request_type_select = document.querySelector("select#id_request_type");
    const update_expense_types = function(event) {
      const request_type = parseInt(request_type_select.value);
      const valid_expense_types = expense_type_map[request_type] || [];
      document.querySelectorAll("select[id$=-expense_type]").forEach(el => {
        el.querySelectorAll("option").forEach(opt => {
          if (opt.value) {
            opt.disabled = !valid_expense_types.includes(parseInt(opt.value));
          }
        });
      });
    };
    request_type_select.addEventListener("input", update_expense_types);
    update_expense_types();
  })();
</script>
{% endblock %}

src/reimbursements/templates/reimbursements/reimburse_request.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load currency_format %}
{% block page_title %}
{% blocktrans with id=object.id subject=object.subject %}
  Reimburse Request {{ id }}: {{ subject }}
{% endblocktrans %}
{% endblock %}
{% block content %}
<h1>
  {% blocktrans with id=object.id subject=object.subject %}
    Reimburse Request {{ id }}: {{ subject }}
  {% endblocktrans %}
</h1>
<h2>{% trans "Bank Details" %}</h2>
<details>
  <summary>{% trans "show/hide" %}</summary>
  <table class="table table-striped">
    {% for k, v in object.bank_details.items %}
      <tr>
        <th>{{ k }}</th>
        <td>{{ v }}</td>
      </tr>
    {% endfor %}
  </table>
</details>
<h2>{% trans "Reimbursement" %}</h2>
<form method="post">
  {% crispy form %}
  <div class="fs-4 pb-3">
    {% trans "Total:" %}
    <span id="total">{% trans "Calculated by Javascript..." %}</span>
  </div>
  <div class="fs-4 pb-3">
    {% trans "Budgeted:" %} <span id="budgeted">{{ object.total | currency }}</span>
    ({% trans "Approved up to:" %} <span id="budget-limit">{{ object.approved_budget_limit | currency }}</span>)
  </div>
  <input type="submit" class="btn btn-primary" value="{% trans 'Reimburse' %}">
</form>
{% endblock %}
{% block extra_foot %}
<script>
  "use strict";
  (function() {
    const budgeted = {{ object.total.0 }};
    const approved_budget_limit = {{ object.approved_budget_limit.0 }};

    const update_total = function(event) {
      var total = 0;
      document.querySelectorAll("input.sum-line").forEach(input => {
        const amount = parseFloat(input.value) || 0;
        total += amount;
      });
      const fmt = new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "{{ object.currency }}",
      });
      const total_span = document.querySelector("span#total");
      total_span.textContent = fmt.format(total);
      document.querySelector("span#budgeted").textContent = fmt.format(budgeted);
      document.querySelector("span#budget-limit").textContent = fmt.format(approved_budget_limit);

      if (total > approved_budget_limit) {
        total_span.classList.add("bg-danger");
      } else {
        total_span.classList.remove("bg-danger");
      }
      if (total > budgeted && total <= approved_budget_limit) {
        total_span.classList.add("bg-warning");
      } else {
        total_span.classList.remove("bg-warning");
      }
    }

    document.querySelectorAll("input.sum-line").forEach(el => {
      el.addEventListener("input", update_total);
    });
    update_total();
  })();
</script>
{% endblock %}

src/reimbursements/templates/reimbursements/request_receipts.html
{% extends 'base.html' %}
{% load i18n %}
{% load currency_format %}
{% block page_title %}
{% blocktrans with id=object.id subject=object.subject %}
  Receipts for request {{ id }}: {{ subject }}
{% endblocktrans %}
{% endblock %}
{% block extra_head %}
<style type="text/css">
.table .xe {
  background-color: #0000ff10;
}
</style>
{% endblock %}
{% block content %}
<h1>
  {% blocktrans with id=object.id subject=object.subject %}
    Receipts for request {{ id }}: {{ subject }}
  {% endblocktrans %}
</h1>
{% for receipt in object.receipts.all %}
  <h2>{{ receipt.subject }}</h2>
  <p>
    <a class="btn btn-warning float-end"
       href="{% url "edit-receipt" object.id receipt.id %}">{% trans "Edit Receipt" %}</a>
    {{ receipt.description|linebreaksbr }}
  </p>
  {% if receipt.file.path.lower|slice:"-4:" == ".pdf" %}
    <object data="{% url "view-receipt-file" object.id receipt.id %}"
            type="application/pdf" width="1296" height="1296">
      <div>
        {% trans "Unfortunately your browser can't display inline PDFs." %}
        <a class="btn btn-info"
            href="{% url "view-receipt-file" object.id receipt.id %}">
          {% trans "Download" %}
        </a>
      </div>
    </object>
  {% else %}
    <img src="{% url "view-receipt-file" object.id receipt.id %}"
         class="img-fluid receipt">
  {% endif %}
  {% if receipt.lines.exists %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>{% trans "Date" %}</th>
          <th>{% trans "Description" %}</th>
          <th>{% trans "Expense Type" %}</th>
          <th class="text-end">{% trans "Amount" %}</th>
          <th class="text-end"
              title="{% trans "Calculated based on the exchange rate of the receipt date" %}">
            {% blocktrans with currency=object.currency %}
              Amount {{ currency }}
            {% endblocktrans %}
          </th>
          {% if object.currency != "USD" %}
            <th class="text-end xe"
                title="{% trans "Calculated based on current exchange rates" %}">
              {% trans "Amount USD" %}
            </th>
          {% endif %}
          {% if object.currency != "EUR" %}
            <th class="text-end xe"
                title="{% trans "Calculated based on current exchange rates" %}">
              {% trans "Amount EUR" %}
            </th>
          {% endif %}
        </tr>
      </thead>
      {% for line in receipt.lines.all %}
        <tr>
          <td>{{ line.date }}</td>
          <td>{{ line.description|linebreaksbr }}</td>
          <td>{{ line.expense_type }}</td>
          <td class="text-end">{{ line.qualified_amount|currency }}</td>
          <td class="text-end">{{ line.qualified_converted_amount|currency }}</td>
          {% if object.currency != "USD" %}
            <td class="text-end xe">{{ line.qualified_converted_amount|exchange:"USD" }}</td>
          {% endif %}
          {% if object.currency != "EUR" %}
            <td class="text-end xe">{{ line.qualified_converted_amount|exchange:"EUR" }}</td>
          {% endif %}
        </tr>
      {% endfor %}
      <tr>
        <th colspan="4">{% trans "Receipt Subtotal" %}</th>
        <td class="text-end">{{ receipt.total|currency }}</td>
        {% if object.currency != "USD" %}
          <td class="text-end xe">{{ receipt.total|exchange:"USD" }}</td>
        {% endif %}
        {% if object.currency != "EUR" %}
          <td class="text-end xe">{{ receipt.total|exchange:"EUR" }}</td>
        {% endif %}
      </tr>
    </table>
  {% endif %}
{% endfor %}
{% endblock %}

src/reimbursements/templates/reimbursements/submit_request.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load currency_format %}
{% block page_title %}
{% trans "Submit Request" %}
{% endblock %}
{% block content %}
<h1>{% trans "Submit Request" %}</h1>
<div>{% trans "By submitting this reimbursement request, I declare:" %}</div>
<form method="post">
  {% crispy form %}
  <input type="submit" class="btn btn-primary" value="{% trans 'Submit' %}">
</form>
{% endblock %}