src/debian_reimbursements/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("registration.backends.default.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("requests/", include("reimbursements.urls")),
    path("", include("webui.urls")),
]

src/webui/urls.py
from django.urls import path

from webui.views import IndexView, ProfileView

urlpatterns = [
    path("", IndexView.as_view()),
    path("profile", ProfileView.as_view(), name="profile"),
]

src/reimbursements/models.py
from collections import defaultdict
from decimal import Decimal

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from historical_currencies.exceptions import ExchangeRateUnavailable
from historical_currencies.exchange import exchange

from reimbursements.storage import generate_receipt_filename, receipts_storage


User = get_user_model()


class SoftDeletionManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class Profile(models.Model):
    bank_details = models.JSONField(blank=True)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"Profile for {self.user}"


class RequestType(models.Model):
    name = models.CharField(max_length=50)
    deleted = models.BooleanField(default=False)

    objects = SoftDeletionManager()
    all_objects = models.Manager()

    def __str__(self):
        return self.name

    @classmethod
    def expense_type_map(cls):
        output = defaultdict(list)
        for row in RequestType.expense_types.through.objects.all():
            output[row.requesttype_id].append(row.expensetype_id)
        return output


class ExpenseType(models.Model):
    request_types = models.ManyToManyField(RequestType, related_name="expense_types")
    name = models.CharField(max_length=50, unique=True)
    deleted = models.BooleanField(default=False)

    objects = SoftDeletionManager()
    all_objects = models.Manager()

    def __str__(self):
        return self.name


class ExpenseTypeAllocation:
    def __init__(
        self, name, currency, requested=0, spent=0, reimbursed=0, special=False
    ):
        self.name = name
        self.currency = currency
        self.requested = Decimal(requested)
        self.spent = Decimal(spent)
        self.reimbursed = Decimal(reimbursed)
        self.special = special

    @property
    def qualified_requested(self):
        return (self.requested, self.currency)

    @property
    def qualified_spent(self):
        return (self.spent, self.currency)

    @property
    def qualified_reimbursed(self):
        return (self.reimbursed, self.currency)

    @property
    def remaining(self):
        return self.requested - self.spent

    @property
    def qualified_remaining(self):
        return (self.remaining, self.currency)

    @property
    def over_budget(self):
        return self.spent > self.requested

    @property
    def within_budget(self):
        return not self.over_budget

    @property
    def approved(self):
        if self.within_budget:
            return self.requested
        return self.requested * (
            1 + Decimal(settings.OVERBUDGET_LEEWAY_PERCENTAGE) / 100
        )

    @property
    def reimburseable(self):
        return min(self.approved, self.spent)

    @property
    def qualified_approved(self):
        return (self.approved, self.currency)

    @property
    def qualified_reimburseable(self):
        return (self.reimburseable, self.currency)

    def to_dict(self):
        return {
            "currency": self.currency,
            "requested": float(self.requested),
            "spent": float(self.spent),
            "reimbursed": float(self.reimbursed),
        }


class Request(models.Model):
    class States(models.TextChoices):
        DRAFT = "draft", _("Draft")
        PENDING_APPROVAL = "pending_approval", _("Pending Approval")
        APPROVED = "approved", _("Approved")
        DELETED = "deleted", _("Deleted")
        PENDING_PAYMENT = "pending_payment", _("Pending Payment")
        PAID = "paid", _("Paid")

    requester = models.ForeignKey(User, on_delete=models.PROTECT)
    parent = models.ForeignKey(
        "Request",
        on_delete=models.PROTECT,
        null=True,
        related_name="children",
        blank=True,
    )
    state = models.CharField(
        max_length=16, choices=States.choices, default=States.DRAFT
    )
    bank_details = models.JSONField(null=True, blank=True)
    request_type = models.ForeignKey(RequestType, on_delete=models.PROTECT)
    description = models.TextField()
    currency = models.CharField(max_length=3, default=settings.DEFAULT_CURRENCY)
    approver_group = models.ForeignKey(
        Group, on_delete=models.PROTECT, null=True, related_name="requests_approver"
    )
    payer_group = models.ForeignKey(
        Group, on_delete=models.PROTECT, related_name="requests_payer"
    )

    @property
    def subject(self):
        lines = self.description.splitlines()
        if lines:
            return lines[0].strip()
        return ""

    @property
    def total(self):
        return (
            self.lines.aggregate(total=models.Sum("amount"))["total"] or Decimal(0),
            self.currency,
        )

    @property
    def receipts_total(self):
        lines = ReceiptLine.objects.filter(receipt__request=self)
        return (
            lines.aggregate(total=models.Sum("converted_amount"))["total"]
            or Decimal(0),
            self.currency,
        )

    @property
    def reimbursed_total(self):
        lines = ReimbursementLine.objects.filter(request=self)
        return (
            lines.aggregate(total=models.Sum("amount"))["total"] or Decimal(0),
            self.currency,
        )

    @property
    def created(self):
        return self.history.get(event=RequestHistory.Events.CREATED).timestamp

    @property
    def updated(self):
        return self.history.all().last().timestamp

    def get_absolute_url(self):
        return reverse("request", kwargs={"pk": self.pk})

    def get_fully_qualified_url(self):
        return settings.SITE_URL.rstrip("/") + self.get_absolute_url()

    def summarize_by_type(self):
        summary = {}
        total = ExpenseTypeAllocation("Total", self.currency, special=True)
        for line in self.lines.all():
            if line.expense_type_id not in summary:
                summary[line.expense_type_id] = ExpenseTypeAllocation(
                    line.expense_type.name, self.currency
                )
            summary[line.expense_type_id].requested += line.amount
            total.requested += line.amount
        for line in self.reimbursement_lines.all():
            if line.expense_type_id not in summary:
                summary[line.expense_type_id] = ExpenseTypeAllocation(
                    line.expense_type.name, self.currency
                )
            summary[line.expense_type_id].reimbursed += line.amount
            total.reimbursed += line.amount
        for receipt in self.receipts.all():
            for line in receipt.lines.all():
                if line.expense_type_id not in summary:
                    summary[line.expense_type_id] = ExpenseTypeAllocation(
                        line.expense_type.name, self.currency
                    )
                summary[line.expense_type_id].spent += line.converted_amount
                total.spent += line.converted_amount
        summary["total"] = total
        return summary

    def summarize_by_type_dict(self):
        allocation = {}
        for k, v in self.summarize_by_type().items():
            allocation[v.name] = v.to_dict()
        return allocation

    @property
    def approved_budget_limit(self):
        """The total requested, plus acceptable leeway"""
        total = self.total[0]
        approved_limit = total * (
            1 + Decimal(settings.OVERBUDGET_LEEWAY_PERCENTAGE) / 100
        )
        return (approved_limit, self.currency)

    @property
    def total_reimburseable(self):
        """The total requested, cut off at approved_budget_limit"""
        approved_total = min(self.approved_budget_limit[0], self.receipts_total[0])
        return (approved_total, self.currency)

    @property
    def within_budget(self):
        budget = self.approved_budget_limit[0]
        receipts_total = self.receipts_total[0]
        return receipts_total <= budget

    @property
    def over_budget(self):
        return not self.within_budget

    def __str__(self):
        return f"Request {self.id}: {self.subject}"

    def user_access(self, user):
        """What access levels does user have to this Request"""
        access = {}
        if self.requester == user:
            access["requester"] = True
        if user.groups.filter(id=self.approver_group_id).exists():
            access["approver"] = True
        if user.groups.filter(id=self.payer_group_id).exists():
            access["payer"] = True
        return access

    @property
    def requester_name(self):
        """Helper for templates, to render the requester's name"""
        name = self.requester.get_full_name()
        if not name:
            name = self.requester.username
        return name


class RequestLine(models.Model):
    request = models.ForeignKey(Request, on_delete=models.CASCADE, related_name="lines")
    expense_type = models.ForeignKey(ExpenseType, on_delete=models.PROTECT)
    description = models.TextField()
    amount = models.DecimalField(decimal_places=2, max_digits=15)

    @property
    def qualified_amount(self):
        return (self.amount, self.request.currency)

    def clean(self):
        super().clean()
        request_type_id = self.request.request_type_id
        if (
            request_type_id
            and self.expense_type_id
            and not self.expense_type.request_types.filter(pk=request_type_id)
        ):
            raise ValidationError(
                {
                    "expense_type": _("%s is not a valid expense type for %s requests")
                    % (self.expense_type.name, self.request.request_type.name),
                }

src/webui/forms.py
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Hidden, Submit
from registration.forms import RegistrationForm

from webui.validators import validate_username


class ReimbursementsRegistrationForm(RegistrationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.include_media = False
        self.helper.form_action = reverse("registration_register")
        self.helper.add_input(Submit("submit", _("Sign up")))

    def clean_username(self):
        username = self.cleaned_data["username"]
        validate_username(username)
        return username


class LoginFormHelper(FormHelper):
    form_action = settings.LOGIN_URL

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if "next" in request.GET:
            self.add_input(Hidden("next", request.GET["next"]))
        self.add_input(Submit("submit", _("Log in")))


class SetPasswordFormHelper(FormHelper):
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_input(Submit("submit", _("Set password")))

src/webui/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView

from reimbursements.models import Request


class IndexView(TemplateView):
    template_name = "index.html"


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviewable = {}
        payable = {}
        for group in self.request.user.groups.all():
            requests = group.requests_approver.filter(
                state=Request.States.PENDING_APPROVAL
            )
            if requests.exists():
                reviewable[group.name] = requests.all()
            requests = group.requests_payer.filter(state=Request.States.PENDING_PAYMENT)
            if requests.exists():
                payable[group.name] = requests.all()
        context["reviewable"] = reviewable
        context["payable"] = payable
        return context

src/webui/templates/base.html
{% load i18n %}
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}
        {{ SITE_NAME }}: {% block page_title %}{% endblock %}
      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
          crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"
          rel="stylesheet"
          integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e"
          crossorigin="anonymous">
    <link rel="icon" type="image/vnd.microsoft.icon" sizes="16x16 24x24 32x32 48x48 64x64"
          href="{% static 'img/favicon/favicon.ico' %}">
    {% block extra_head %}{% endblock %}
  </head>
  <body class="d-flex flex-column h-100">
    {% include "nav.html" %}
    <div class="container-xxl">
      {% block content %}I am a page without a content block{% endblock %}
    </div>
    <footer class="footer bg-light mt-auto py-1">
      <div class="container-xxl">
        <p>
          {% blocktrans %}
            {{ SITE_NAME }}: An instance of
            <a href="https://salsa.debian.org/stefanor/debian-reimbursement">debian-reimbursement</a>.
            Please file bugs <a href="https://salsa.debian.org/stefanor/debian-reimbursement/-/issues">here</a>.
          {% endblocktrans %}
        </p>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
            crossorigin="anonymous"></script>
    {% block extra_foot %}{% endblock %}
  </body>
</html>

src/webui/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{{ SITE_NAME }}{% endblock %}
{% block content %}
<h1>{{ SITE_NAME }}</h1>
{% if SITE_PROD_STATE == "dev" %}
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">
      <i class="bi bi-exclamation-triangle-fill"></i>
      {% trans "Development System" %}
    </h4>
    <p>
      {% blocktrans %}
        This is an experimental, in-development system.
        It isn't being used for anything real.
        Don't believe anything it says, or expect data to be persistant.
      {% endblocktrans %}
    </p>
  </div>
{% elif SITE_PROD_STATE == "beta" %}
  <div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">
      <i class="bi bi-exclamation-triangle-fill"></i>
      {% trans "Development System" %}
    </h4>
    <p>
      {% blocktrans %}
        This is still an experimental in-development system.
        It is being used to test out a future replacement to the RT-based
        reimbursement flows.
      {% endblocktrans %}
    </p>
    <p>
      {% blocktrans %}
        This process is being tested by a couple of specific teams.
        If you haven't been directly invited to use it, please use the RT-based
        process, for now.
      {% endblocktrans %}
    </p>
    <p>
      {% blocktrans %}
        You may encounter bugs.
        Please file them <a
          href="https://salsa.debian.org/stefanor/debian-reimbursement/-/issues">here</a>.
      {% endblocktrans %}
    </p>
  </div>
{% endif %}
<h2>{% trans "The process" %}</h2>
<p>
  {% blocktrans %}
    This system lets you request approval for expenses, collect receipts, and
    receive reimbursement. The process is:
  {% endblocktrans %}
</p>
<ol>
  <li>
    {% url "request-new" as file_url %}
    {% blocktrans %}
      <a class="btn btn-primary" href="{{ file_url }}">File</a>
      File a pre-approval request.
    {% endblocktrans %}
  </li>
  <li>{% trans "Receive approval from the DPL." %}</li>
  <li>{% trans "Make the expenses, up to the approved amount." %}</li>
  <li>{% trans "Upload receipts for the expenses." %}</li>
  <li>{% trans "Submit the receipts and request reimbursement." %}</li>
  <li>{% trans "Receive reimbursement from a Debian TO." %}</li>
</ol>
{% endblock %}

src/webui/templates/nav.html
{% load i18n %}
<nav class="navbar navbar-expand-lg sticky-top {% if SITE_PROD_STATE == "dev" %}bg-danger{% else %}bg-light{% endif %}">
  <nav class="container-xxl">
    <a class="navbar-brand" href="/">{{ SITE_NAME }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        {% if request.user.is_authenticated %}
	  <li class="nav-item">
	    <span class="nav-link">
	      <i class="bi bi-person-fill"></i> {{ user.username }}
	    </span>
	  </li>
          <li class="nav-item">
            <a class="nav-link" href="/profile">{% trans "Profile" %}</a>
          </li>
          {% if request.user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="/admin">{% trans "Admin" %}</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="/accounts/logout">{% trans "Log Out" %}</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/accounts/login">{% trans "Log In" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/accounts/register">{% trans "Create Account" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</nav>

src/webui/templates/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% block page_title %}{% trans 'Profile' %}{% endblock %}
{% block content %}
<h1>{% trans 'Profile' %}</h1>
<h2>{% trans 'My Requests' %}</h2>
<ul>
  {% for request in request.user.request_set.all %}
    <li>
      {% translate "View" as action %}
      {% include "includes/request-list-item.html" with request=request action=action %}
    </li>
  {% empty %}
    <li>{% trans 'No previous requests' %}</li>
  {% endfor %}
</ul>
<a href="{% url "request-new" %}" class="btn btn-secondary">New Request</a>
{% if reviewable %}
  <h2>{% trans 'Reviewable Requests' %}</h2>
  {% for group, requests in reviewable.items %}
    <h3>
      {% blocktrans with group=group %}
        For {{ group }}
      {% endblocktrans %}
    </h3>
    <ul>
      {% for request in requests %}
        <li>
          {% translate "Review" as action %}
          {% include "includes/request-list-item.html" with request=request %}
        </li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endif %}
{% if payable %}
  <h2>{% trans 'Payable Requests' %}</h2>
  {% for group, requests in payable.items %}
    <h3>
      {% blocktrans with group=group %}
        For {{ group }}
      {% endblocktrans %}
    </h3>
    <ul>
      {% for request in requests %}
        <li>
          {% translate "Pay" as action %}
          {% include "includes/request-list-item.html" with request=request %}
        </li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endif %}
{% endblock %}